app_info:
  # APP名称
  appName: xxxxx
  # APP包名
  appPackage: xxx.xxx.xxx
  # APP程序名
  appActivity: xxx.xxx.xxx
device_info:
  # 设备版本号
  platformVersion: 10.0
  # 设备id
  deviceName: xxx.xxx.xxx
appium_info:
  #appium所在ip以及端口号
  appiumIp: http://127.0.0.1:4723/wd/hub
